site_name: PyFV3 Documentation
site_url: https://noaa-gfdl.github.io/PyFV3/
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [./pyfv3]  # Adjust this path to where your Python modules are
          options:
            show_source: false
            show_root_heading: false

nav:
  - Home: index.md
  - Top:
      - "_config": top/_config.md
      - "dycore_state": top/dycore_state.md
      - "version": top/version.md
  - Stencils:
      - "a2b_ord4": stencils/a2b_ord4.md
      - "c_sw": stencils/c_sw.md
      - "d2a2c_vect": stencils/d2a2c_vect.md
      - "d_sw": stencils/d_sw.md
      - "del2cubed": stencils/del2cubed.md
      - "delnflux": stencils/delnflux.md
      - "divergence_damping": stencils/divergence_damping.md
      - "dyn_core": stencils/dyn_core.md
      - "fillz": stencils/fillz.md
      - "fv_dynamics": stencils/fv_dynamics.md
      - "fv_subgridz": stencils/fv_subgridz.md
      - "fvtp2d": stencils/fvtp2d.md
      - "fxadv": stencils/fxadv.md
      - "map_single": stencils/map_single.md
      - "mapn_tracer": stencils/mapn_tracer.md
      - "moist_cv": stencils/moist_cv.md
      - "neg_adj3": stencils/neg_adj3.md
      - "nh_p_grad": stencils/nh_p_grad.md
      - "pe_halo": stencils/pe_halo.md
      - "pk3_halo": stencils/pk3_halo.md
      - "ppm": stencils/ppm.md
      - "ray_fast": stencils/ray_fast.md
      - "remap_profile": stencils/remap_profile.md
      - "remapping": stencils/remapping.md
      - "riem_solver3": stencils/riem_solver3.md
      - "riem_solver_c": stencils/riem_solver_c.md
      - "saturation_adjustment": stencils/saturation_adjustment.md
      - "sim1_solver": stencils/sim1_solver.md
      - "temperature_adjust": stencils/temperature_adjust.md
      - "tracer_2d_1l": stencils/tracer_2d_1l.md
      - "updatedzc": stencils/updatedzc.md
      - "updatedzd": stencils/updatedzd.md
      - "xppm": stencils/xppm.md
      - "xtp_u": stencils/xtp_u.md
      - "yppm": stencils/yppm.md
      - "ytp_v": stencils/ytp_v.md
  - Utils:
      - "functional_validation": utils/functional_validation.md
  - Wrappers:
      - "geos_wrapper": wrappers/geos_wrapper.md

markdown_extensions:
  # simple glossary file
  - abbr
  # support for colored notes / warnings / tips / examples
  - admonition
  # emoji support
  - attr_list
  # support for footnotes
  - footnotes
  # supercharges admonitions by making them collapsible
  - pymdownx.details
  # support for syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  # support for task list of the form `- [ ] task name`
  - pymdownx.tasklist:
      custom_checkbox: false
