[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 77.0.3"]

[project]
authors = [{name = "NOAA - Geophysical Fluid Dynamics Laboratory", email = "oliver.elbert@noaa.gov"}]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11"
]
dependencies = [
  "f90nml>=1.1.0",
  "numpy==1.26.4",
  "xarray"
]
description = "PyFV3 is a NDSL-based FV3 dynamical core for atmospheric models."
license = "Apache-2.0"
license-files = ["LICENSE.md"]
name = "pyfv3"
readme = "README.md"
requires-python = ">=3.11,<3.12"
version = "0.2.0"

[project.optional-dependencies]
dev = [
  "pyfv3[docs,ndsl,test]",
  "pre-commit",
  "flake8-pyproject"
]
docs = [
  "mkdocs-material",
  "mkdocstrings[python]"
]
extras = [
  "pyfv3[dev]",
  "pyfv3[docs]",
  "pyfv3[ndsl]",
  "pyfv3[test]"
]
# TODO: Revert ndsl back to GFDL develop (not jjuyeonkim) after merging https://github.com/NOAA-GFDL/NDSL/issues/64
ndsl = ["ndsl @ git+https://github.com/jjuyeonkim/NDSL.git@20250908_namelist_2"]
test = [
  "coverage",
  "pytest",
  "pytest-subtests",
  "serialbox"
]

[project.urls]
# TODO: Revert repo back to GFDL develop (not jjuyeonkim) after merging https://github.com/NOAA-GFDL/NDSL/issues/64
Repository = "https://github.com/jjuyeonkim/pyFV3"

[tool.aliases]

[tool.black]
line-length = 88
target_version = ['py311']

[tool.coverage.run]
branch = true
omit = ["tests/*", "*gt_cache*", ".dacecache*", "external/*", "__init__.py"]
parallel = true
source_pkgs = ["pyfv3"]

[tool.flake8]
exclude = ["docs"]
extend-ignore = ["W503", "E302", "E203", "F841", "E501"]
max-line-length = 88

[tool.isort]
default_section = "THIRDPARTY"
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = "pyfv3,ndsl,pyshield"
known_third_party = "f90nml,pytest,xarray,numpy,mpi4py,gt4py"
line_length = 88
lines_after_imports = 2
multi_line_output = 3
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
use_parentheses = true

[tool.mypy]
exclude = ["pyfv3/stencils/fv_subgridz.py", "tests/conftest.py"]
explicit_package_bases = true
follow_imports = "normal"
ignore_missing_imports = true
namespace_packages = true
strict_optional = false
warn_unreachable = true

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["pyfv3", "pyfv3.*"]
