[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "pyfv3"
version = "0.2.0"
dependencies = [
    "f90nml>=1.1.0",
    "numpy==1.26.4",
    "xarray",
]
requires-python = ">=3.11,<3.12"
authors = [{name = "NOAA - Geophysical Fluid Dynamics Laboratory", email = "oliver.elbert@noaa.gov"}]
description = "PyFV3 is a NDSL-based FV3 dynamical core for atmospheric models."
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE.md"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
]

[project.optional-dependencies]
test = [
    "coverage",
    "pytest",
    "pytest-subtests",
    "serialbox",
]
ndsl = ["ndsl @ git+https://github.com/NOAA-GFDL/NDSL.git@develop"]
develop = [
    "pyfv3[test]",
    "pyfv3[ndsl]",
    "pre-commit",
]
extras = [
    "pyfv3[test]",
    "pyfv3[ndsl]",
    "pyfv3[develop]",
]

[project.urls]
Repository = "https://github.com/NOAA-GFDL/pyFV3"

[tool.setuptools.packages.find]
include = ["pyfv3", "pyfv3.*"]

[tool.setuptools]
include-package-data = true

[tool.black]
line-length = 88
target_version = ['py311']
