# TODO: Re-activate after PR 60
# TODO: Temporarily removing tests due to dependent changes in
#       Pace#129, PyFV3#64 PRs; tests should be reverted back after
#       these PRs are merged.

# name: "pace main tests"
# on:
#   pull_request:

# jobs:
#   pace_main_tests:
#     uses: NOAA-GFDL/pace/.github/workflows/main_unit_tests.yaml@develop
#     with:
#       component_trigger: true
#       component_name: pyFV3